### ISSUE TITLE
Video-Fullscreen

### ISSUE THREAD

**Issue by frogg** [noestreich/Telemac#1]
Es sollte eine Möglichkeit geben einen Video-Stream im Vollbild zu öffnen (sodass alle anderen Bedienelemente ausgeblendet sind).
Gibt es da eine Art "JavaScript-Callback" vom MacGap-Framework, wenn die Mac App in den Vollbildmodus versetzt wird? Vielleicht könnte man das darüber verknüpfen.

**Comment by noestreich** [comment]
Leider nein. 
Zwar bietet Macgap zwei eigentlich [brauchbare Methoden](http://docs.macgap.com/ref/window.html) an: 
`MacGap.Window.maximize() und MacGap.Window.toggleFullscreen()`

Diese scheinen unter OS X 10.11 jedoch nicht mehr zu funktionieren. 

Wahrscheinlich wird langfristig kein Weg am Wechsel auf [Electron](http://electron.atom.io) vorbeiführen. 

Alternativ könnte man den laufenden Sender in ein Pop-Out-Fenster verlagern (so wie jetzt schon das TV-Programm) und dieses dann zu 100% vom Video füllen lassen. Dafür ist der durchschnittliche Nutzer aber vielleicht zu sehr am Schalten...?

**Comment by noestreich** [comment]
Übergangslösung: Rechte Maustaste aufs Video -> Enter Fullscreen. 
HIer gibt es allerdings einen Bug. Verlässt man den Fullscreen-Modus wieder, läuft der Ton im Hintergrund weiter. Einziger Ausweg. Neustart der App.

**Comment by frogg** [comment]
Ansonsten ist meine Idee: Über Xcode eine Mac App erstellen und da ein `WKWebView` mit der html Datei laden und dann die entsprechenden Callbacks von Objective C abfangen und an das WebView weiterleiten. Das ging glaube ich so: `[webView stringByEvaluatingJavaScriptFromString:@"toggleFullscreen();"];`

**Comment by frogg** [comment]
Habe es mal geforked und in ein Xcode Projekt in ein WebView eingebunden.
https://github.com/quappi/Telemac

Es gibt jetzt zwei Javascript-Callbacks in der `ViewController.m` Datei in Zeile 32 bis 38.

**Comment by noestreich** [comment]
Genial. Schaue ich die Woche drauf.

**Comment by noestreich** [comment]
Native Video-Fullscreen is enabled in Version 2.3
