### ISSUE TITLE
"Immer im Vordergrund"

### ISSUE THREAD

**Issue by manuallypure** [noestreich/Telemac#10]
Ich würde mir eine "Immer im Vordergrund" Funktion wünschen. Da ich beim TV schauen immer gerne im Netz surfe und somit den Firefox benutze, wäre es super, wenn man das Bild immer im Vordergrund halten könnte.

**Comment by noestreich** [comment]
Ist in Umsetzung. Probier bitte mal die folgende Beta aus und gib eine kurze Rückmeldung. 
[Telemac_2.5_beta.zip](https://github.com/noestreich/Telemac/files/970785/Telemac_2.5_beta.zip)
Manuelles aktivieren / deaktivieren ist geplant.

**Comment by manuallypure** [comment]
Cool, scheint zu funktionieren. Ja, manuelles aktivieren/deaktivieren wäre natürlich noch besser.

Danke!
