### ISSUE TITLE
"France 24" Stream Link tot

### ISSUE THREAD

**Issue by manuallypure** [noestreich/Telemac#11]
Hey,

der France24 Link funktioniert nicht mehr.

Gibt es eine einfache Möglichkeit, Links selbst zu aktualisieren?

**Comment by noestreich** [comment]
Wird gerichtet. Der aktuelle Link ist: 
`http://static.france24.com/live/F24_EN_HI_HLS/live_tv.m3u8`
Wenn du nicht bis zum nächsten Release warten willst kannst du diese manuell in
[/public/assets/js/sendersrc.js](https://github.com/noestreich/Telemac/blob/master/public/assets/js/sendersrc.js) aktualisieren.
