### ISSUE TITLE
"Stumm-Schalter" bitte implementieren

### ISSUE THREAD

**Issue by manuallypure** [noestreich/Telemac#12]
Es wäre super, wenn ihr noch einen Stummschalter einbauen könntet, damit man Telemac nicht jedesmal komplett schließen muss, wenn man zum Beispiel Spotify hören will oder einfach ohne Ton weiter Telemac schauen will. Das kommt öfters vor als man glaubt :)

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
