### ISSUE TITLE
NTV

### ISSUE THREAD

**Issue by mountbatt** [noestreich/Telemac#13]
Gibts Gründe warum N-TV nicht mit dabei ist? http://www.n-tv.de/mediathek/livestream/

**Comment by seisfeld** [comment]
Also da N24 ja auch dabei ist, wüsste ich nicht warum n-tv nicht auch dabei sein kann. Was wir bräuchten wäre eine Grafik, dann kann ich einen PR dafür fertig machen. @noestreich

**Comment by mountbatt** [comment]
N24 heißt jetzt WELT - da müsste dann auch ne neue Grafik her …

**Comment by mountbatt** [comment]
Hab mal in Photoshop 2 Logos nachgebaut … vielleicht passen die ja einigermaßen … @noestreich

![n-tv](https://user-images.githubusercontent.com/2411246/35509568-f0bd2260-04f4-11e8-97f5-fcb0b23da9a5.png)
![welt](https://user-images.githubusercontent.com/2411246/35509569-f0ec3c80-04f4-11e8-8cbe-9cc404381b34.png)

Ich geb zu, die treffen nicht ganz den Style der anderen … fehlt mir jetzt nur die Zeit für. Just a little helper … :)

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
