### ISSUE TITLE
Kika Livestream

### ISSUE THREAD

**Issue by Isob-zz-uster** [noestreich/Telemac#14]
Der Kika-Livestream geht nicht mehr. Kika hat auf einen anderen Livestream gewechselt: http://www.kika.de/videos/livestream/livestream110.html

**Comment by seisfeld** [comment]
Ich habe die URL gewechselt und einen PR aufgemacht. @noestreich

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
