### ISSUE TITLE
Livestreams funktionieren nicht

### ISSUE THREAD

**Issue by Isob-zz-uster** [noestreich/Telemac#16]
Bei den Livestreams von **WDR**, **One** und **MDR** bleibt das Bild schwarz. Beim Livestream von **NDR** gibt es die Fehlermeldung "_The video could not be loaded, either because the server or network failed or because the format is not supported._"

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
