### ISSUE TITLE
Bei mir gehen mehrere Streams nicht

### ISSUE THREAD

**Issue by taijm** [noestreich/Telemac#18]
Erstmals danke für das Programm, prima gemacht, schlank und effektiv. Nur den Lautstärkeregler vermisse ich.

Seit einiger Zeit gehen vor allem ARD Programme nicht mehr. Neuinstallation mit davor gelöschten Präferenzen brachte nichts. Um eine Anleitung zu finden bin ich zu blond, sorry.
![Bildschirmfoto 2019-04-18 um 10 43 40](https://user-images.githubusercontent.com/49748351/56348710-55f4bf00-61c7-11e9-8d48-8d95214b82d0.png)

**Comment by romlos** [comment]
Habe das gleiche Problem mit den ARD-Programmen. Gibt es hierfür eine Lösung @noestreich ?

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
