### ISSUE TITLE
performance player 

### ISSUE THREAD

**Issue by justvanbloom** [noestreich/Telemac#4]
to get most best out of our player maybe  [hls.js](https://github.com/dailymotion/hls.js/tree/master) is better?

we can also use the new detach video function on 10.12 then..

**Comment by noestreich** [comment]
Half of the currently supported telemac-streams don't comply to the m3u-spec hls.js is expecting and thus provoking errors while switching sources. I think, right now, hls.js (0.6.6) is sadly not an option.
