### ISSUE TITLE
Feature Request: add telemac to `brew cask`

### ISSUE THREAD

**Issue by muescha** [noestreich/Telemac#5]
Feature Request: add telemac to `brew cask` so that i can install the app with `brew cask install telemac`

https://github.com/caskroom/homebrew-cask

**Comment by justvanbloom** [comment]
Ok, i'll give it a try.

**Comment by justvanbloom** [comment]
i am right?

cask 'telemac' do
  version '2.4'
  sha256 'eec021b9e13d59c8858b91203e85cf5f00383fc876d37f40c83fe87e008ea5d1'

  url 'https://github.com/justvanbloom/Telemac/blob/master/Releases/Telemac_2.4.zip?raw=true'
  name 'Telemac'
  homepage 'https://github.com/noestreich/Telemac'

  app 'Telemac.app'
end

**Comment by muescha** [comment]
i don't know exactly - the best is to add a pull request to brew cask

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
