### ISSUE TITLE
Senderlogos

### ISSUE THREAD

**Issue by sstaub** [noestreich/Telemac#6]
Schön wäre es wenn man alternativ auf die alten originale Senderlogos umschalten könnte. Die selbstgestrickten sind weder schön noch besonders leserlich (MacBook Pro 15'' Retina).

**Comment by noestreich** [comment]
Danke für den Input. Kann ich leider nicht umsetzen, dafür ist mir die Rechtelage zu unsicher. Kannst du aber einfach selber austauschen. [Hier gibt es die Logos](https://github.com/3PO/Senderlogos) tauschen musst du die Dateien in Telemac/public/assets/tvlogos

**Comment by sstaub** [comment]
Danke für den Hinweis.
