### ISSUE TITLE
Senderauswahl im Vollbildmodus unmöglich

### ISSUE THREAD

**Issue by Mindsuk** [noestreich/Telemac#8]
Hallo, 

es ist mir nicht möglich, im Vollbild mit der Maus die Senderlogos zu erreichen. Wenn ich kurz davor bin, wird die Leiste schon ausgeblendet.. :(

Grüße

**Comment by noestreich** [comment]
Oh ha. Guter Punkt - war anscheinend schon in der Vorgängerversion ein Problem. Mist ;)

Vorübergehende Notlösung, wenn du selbst Hand anlegen willst: Den ".controls {}"-Block im CSS um die folgende Zeile ergänzen: 
`max-width: 890px;`
Und zwar [in dieser Datei](https://github.com/noestreich/Telemac/blob/master/public/assets/css/style.css). Ich schreib das für die 2.5 auf die Liste.

**Comment by Mindsuk** [comment]
Danke, jetzt funktioniert es! 

Allerdings fand ich die Darstellung des Overlays bei der Bildschirmgröße vorher besser.

vorher:
![bildschirmfoto 2017-04-25 um 10 56 05](https://cloud.githubusercontent.com/assets/27997724/25376830/d402b1d8-29a5-11e7-93b3-3e48c203ac7e.jpg)


nachher: 
![bildschirmfoto 2017-04-25 um 10 52 46](https://cloud.githubusercontent.com/assets/27997724/25376779/a6639756-29a5-11e7-910a-1afee8757768.jpg)

**Comment by noestreich** [comment]
Ah, ich sehe. Dann entferne die Zeile und setzt dafür die folgende ein: 
` min-height: 21%;`

# Zur Erklärung: 
Die Sender werden angezeigt sobald der Mauszeiger in die hier aufgezeichnete Hitbox hineingefahren ist (80% der aktuellen Fenstergröße) und wieder ausgeblendet wenn der Mauszeiger sich wieder aus dem aktiven Bereich bzw. von den Programmtasten entfernt. Dies kann bei großen Monitoren zu dem beobachteten Effekt führen. 

![hitbox](https://cloud.githubusercontent.com/assets/309419/25378781/5bbc3536-29ab-11e7-923e-fff041a54e14.jpg)

Wenn du also sagst, dass die Programm-Tasten mindestens 21% vom Bild ausfüllen sollten, dann müsste es klappen. Hier siehts OK aus. Müsse noch "schön" gemacht werden.

**Comment by Mindsuk** [comment]
Danke, schon viel besser :)

![bildschirmfoto 2017-04-25 um 11 44 37](https://cloud.githubusercontent.com/assets/27997724/25379368/16d57002-29ad-11e7-8b35-1240dc2c4fca.jpg)

**Comment by noestreich** [comment]
Na los, dann änder noch die Zeile, dann ist auch der Hintergrund der Programmtasten transparent und alles ist wieder halbwegs augenfreundlich und funktional ;)
`    background-color: rgba(0, 0, 0, 0);`

**Comment by Mindsuk** [comment]
wunderbar! 👍

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
