### ISSUE TITLE
Bildgröße

### ISSUE THREAD

**Issue by like-telemac** [noestreich/Telemac#9]
Hallo, ich würde mir wünschen, man könnte das Bild noch kleiner ziehen. Wie z.B. QuickTime. Ist ca. nur noch 1/3 von der minimalen Größe die man im Moment einstellen kann. Warum? Ich nutze Telemac während dem Surfen oder anderen Anwendungen und mir würde ein kleines Bild in einer Ecke des 15" Bildschirmes reichen. Wäre schön wenn sich das realsieren lassen könnte. Vielen Dank & VG.

**Comment by manuallypure** [comment]
das kann ich nur unterschreiben. Ein noch kleineres Bild wäre wirklich toll. Dann müsste man das Fenster nicht so oft verschieben :)

**Comment by noestreich** [comment]
Die Mac-App wird nicht mehr weiterentwickelt uns lebt fortan als Webseite weiter.
Hier die [Live-Version](https://telemat.1mb.site/),  hier das [Repository](https://github.com/noestreich/Teleweb).
